source "azure-arm" "autogenerated_1" {
  azure_tags = {
    env = "dev"
  }
#  boot_command = [
#    "inst.text inst.ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks.cfg"
#  ]
  client_id                         = "64dca93a-148e-4a35-aabc-8e05bd2b944f"
  client_secret                     = "2eV8Q~Y-N1a2NuKr6.xYYcDtLn1eSxYXwY5kndvo"
  tenant_id                         = "1ea1c520-b78c-4463-b9d4-d8d99073052c"
  subscription_id                   = "c6a76d9c-0f67-4a42-b2a1-3defb05f2aae"
  os_type                           = "Linux"
  image_offer                       = "rockylinux-x86_64"
  image_publisher                   = "resf"
  image_sku                         = "rockylinux-x86_64-9"
  location                          = "North Europe"
  managed_image_name                = "rl9"
  managed_image_resource_group_name = "rg-packer"
  vm_size                           = "Standard_DS2_v2"
  plan_info {
    plan_name = "rockylinux-x86_64-9"
    plan_product = "rockylinux-x86_64"
    plan_publisher ="resf"
  }
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "shell" {
    execute_command = "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'"
    inline          = ["dnf -y update", "dnf install -y epel-release", "dnf install ansible -y"]
    inline_shebang  = "/bin/sh -x"
  }
}

packer {
  required_plugins {
    azure = {
      source  = "github.com/hashicorp/azure"
      version = ">= 2.0.2"
    }
  }
}
