name: Delete Resource group

on:
  workflow_dispatch:
    inputs:
      approve_deletion:
        description: "Delete the resource group"
        required: true
        type: choice
        options:
          - "approve"

env:
  RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}

jobs:
  delete_infrastrucutre:
    runs-on: ubuntu-20.04

    steps:

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Delete Resource group
        id: delete_rg
        run: |
          az group delete \
            --name ${{ env.RESOURCE_GROUP_NAME }} \
            --yes