name: Delete Resource group

on:
  workflow_dispatch:
    inputs:
      stage:
        description: "Deployment Stage"
        required: true
        type: choice
        options:
          - "dev"
          - "prod"

env:
  RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}

jobs:
  create_infrastrucutre:
    runs-on: ubuntu-20.04

    steps:

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Delete Resource group
        id: delete_rg
        # if: always()
        run: |
          az group delete \
            --name ${{ env.RESOURCE_GROUP_NAME }} \
            --yes