name: Rl9

on:
  workflow_dispatch:
    inputs:
      stage:
        description: "Deployment Stage"
        required: true
        type: choice
        options:
          - "dev"
          - "prod"
  push:
    branches:
      - main
      - feature/live_image_caching

env:
  PRODUCT_VERSION: ${{ vars.PRODUCT_VERSION }}
  VM_NAME: ${{ vars.VM_NAME }}
  VM_USER_NAME: ${{ vars.VM_USER_NAME }}
  QEMU_IMAGE_OUTPUT_DIR: ${{ vars.QEMU_IMAGE_OUTPUT_DIR }}
  QCOW2_IMAGE_NAME: ${{ vars.QCOW2_IMAGE_NAME }}

jobs:
  build_live_image:
    uses: ./.github/workflows/build-image.yml
    with:
      stage: ${{ github.event.inputs.stage }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  run_tests:
    runs-on: ubuntu-20.04
    needs: build_live_image
    strategy:
      matrix:
        cis_test: 
          - cis_test_1.sh
          - cis_test_2.sh

    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v4       

      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
            name: rocky_image

      - name: Install KVM virtualization
        id: install_kvm
        run: |
          chmod +x scripts/install_kvm.sh
          bash scripts/install_kvm.sh

      - name: Run Qemu VM
        id: run_vm
        run: |
          ls -l
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > rocky_rsa
          chmod 600 rocky_rsa
          chmod +x scripts/run_vm.sh
          bash scripts/run_vm.sh rocky_rsa ${{ github.workspace }}/tests/${{ matrix.cis_test }} ${{ env.VM_USER_NAME }} ${{ env.QCOW2_IMAGE_NAME }}

      - name: Upload test output as artifact
        id: upload_test_output
        uses: actions/upload-artifact@v4
        with:
          name: test-output-${{ matrix.cis_test }}
          path: cis_test_outputs

      - name: Shutdown a VM
        id: shutdown_vm
        run: |
          chmod +x scripts/shutdown_vm.sh
          bash scripts/shutdown_vm.sh
