name: Build and Deploy Azure VM Image

on:
  push:
    branches:
      - main

env:
  PRODUCT_VERSION: "1.10.1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v4

      - name: Set up Packer
        id: setup_packer
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run `packer init`
        id: init_packer
        run: "packer init ./rl9.pkr.hcl"

      - name: Run `packer validate`
        id: validate_packer
        run: "packer validate ./rl9.pkr.hcl"

      - name: Build Image
        id: build_image
        run: packer build -var 'azure_client_id=${{ secrets.AZURE_CLIENT_ID }}' -var 'azure_client_secret=${{ secrets.AZURE_CLIENT_SECRET }}' -var 'azure_tenant_id=${{ secrets.AZURE_TENANT_ID }}' -var 'azure_subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}' ./rl9.pkr.hcl

      - name: Create Resource group
        id: create_resource_group
        run: |
          az group create -n pg-packer-vm -l northeurope

      - name: Create VM
        id: create_vm
        run: |
          az vm create \
          --resource-group pg-packer-vm \
          --location northeurope \
          --name packer-rl9 \
          --image rl9 \
          --admin-username azureuser \
          --generate-ssh-keys

      - name: Open VM port
        id: open_vm_port
        run: |
          az vm open-port \
          --resource-group pg-packer-vm \
          --name packer-rl9 \
          --port 22