name: CIS tests with Packer Azure VM Image

on:
  workflow_dispatch:
    inputs:
      stage:
        description: "Deployment Stage"
        required: true
        type: choice
        options:
          - "dev"
          - "prod"
  push:
    branches:
      - main
      - feature/live_image

env:
  PRODUCT_VERSION: ${{ vars.PRODUCT_VERSION }}
  QEMU_IMAGE_OUTPUT_DIR: ${{ vars.QEMU_IMAGE_OUTPUT_DIR }}
  QCOW2_IMAGE_NAME: ${{ vars.QCOW2_IMAGE_NAME }}

jobs:
  build_packer_image:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v4

      - name: Install KVM virtualization
        id: install_kvm
        run: |
          chmod +x install_kvm.sh
          sudo -E ./install_kvm.sh

      - name: Set up Packer
        id: setup_packer
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init_packer
        run: packer init .

      - name: Run `packer validate`
        id: validate_packer
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > rocky_rsa
          chmod 400 rocky_rsa
          packer validate -var-file="dev.pkrvars.hcl" \
                          -var 'ssh_private_key_file=rocky_rsa' \
                          .
                          
      - name: Build Image
        id: build_packer_image
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > rocky_rsa
          chmod 600 rocky_rsa
          PACKER_LOG=1 packer build -var-file="dev.pkrvars.hcl" \
                                    -var 'ssh_private_key_file=rocky_rsa' \
                                    -force .

      - name: Run Qemu VM
        id: run_vm
        run: |
          chmod +x run-vm.sh
          sudo -E ./run-vm.sh

      - name: Run CIS test
        id: cis_test
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > rocky_rsa
          chmod 400 rocky_rsa
          echo "test ssh connection"
          ssh -V -o StrictHostKeyChecking=no \
              -i rocky_rsa \
              -p 3777 \
              localhost 'bash -s' < cis-script.sh > output.json
          cat output.json

      - name: Upload output as artifact
        id: cis_test_output
        uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: output.json

      - name: Stop and Shutdown a VM
        id: stop_shutdown_vm
        run: |
          echo $(virsh list)
          id=$(virsh list | awk 'NR>2 {print $2}')
          echo "-------"
          echo $id
          echo "-------"
          virsh shutdown $id
