name: CIS tests with Packer Azure VM Image

on:
  repository_dispatch:
  push:
    branches:
      - main
      - feature/ga_packer_vm_cis_test

env:
  PRODUCT_VERSION: "1.10.1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check if Packer cfg is changed
        id: check_if_files_changed
        run: |
          pwd
          # Diff HEAD with the previous commit
          diff=$(git diff --name-only HEAD~1 HEAD)
          echo $diff

          # Check if a files with the .pkr.hcl extension have changed
          source_diff=$(echo "$diff" | grep -E '\.pkr.hcl$')
          have_diff=false
          echo $source_diff

          # Check if there are changes
          if [ -n "$source_diff" ]; then
           have_diff=true
          fi
          echo $have_diff

          # Set the output named "pkr_cfg_changed"
          echo "::set-output name=pkr_cfg_changed::$have_diff"

      - name: Set up Packer
        id: setup_packer
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run `packer init`
        id: init_packer
        run: "packer init ./rl9.pkr.hcl"

      - name: Run `packer validate`
        id: validate_packer
        run: "packer validate ./rl9.pkr.hcl"

      - name: Build Image
        id: build_packer_image
        if: steps.chack_file_changed.outputs.pkr_cfg_changed == true
        run: packer build ./rl9.pkr.hcl

      - name: Create VM Resource group
        id: create_vm_resource_group
        run: |
          az group create -n rg-packer-vm -l northeurope

      - name: Create VM
        id: create_vm
        run: |
          az vm create \
            --resource-group rg-packer-vm \
            --location northeurope \
            --name packer-rl9 \
            --image /subscriptions/c6a76d9c-0f67-4a42-b2a1-3defb05f2aae/resourceGroups/rg-packer/providers/Microsoft.Compute/images/rl9 \
            --nic-delete-option delete \
            --os-disk-delete-option delete \
            --plan-name rockylinux-x86_64-9 \
            --plan-product rockylinux-x86_64 \
            --plan-publisher resf \
            --admin-username azureuser \
            --generate-ssh-keys

      - name: Open VM SSH port
        id: open_vm_ssh_port
        run: |
          az vm open-port \
          --resource-group rg-packer-vm \
          --name packer-rl9 \
          --port 22      

      - name: Run CIS Rocky Linux tests
        id: cis_tests
        run: |
          PUBLIC_IP=$(az vm show \
            --show-details \
            --resource-group rg-packer-vm \
            --name packer-rl9 \
            --query publicIps \
            --output tsv)
          ssh-keyscan -H -t rsa ${PUBLIC_IP}  >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa azureuser@${PUBLIC_IP} 'bash -s' < test-script.sh

      - name: Shutdown and dismantle VM
        if: always()
        id: shutdown_dismantle_vm
        run: |
          az vm deallocate \
            --resource-group rg-packer-vm \
            --name packer-rl9
          az vm delete \
            --resource-group rg-packer-vm \
            --name packer-rl9 \
            --force-deletion none \
            --yes

      - name: Delete VM Resource group
        id: delete_vm_rg
        run: |
          az group delete \
            --name rg-packer-vm \
            --yes