name: Build and Deploy Azure VM Image

on:
  push:
    branches:
      - main

env:
  PRODUCT_VERSION: "1.10.1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v4

      - name: Set up Packer
        id: setup_packer
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run `packer init`
        id: init_packer
        run: "packer init ./rl9.pkr.hcl"

      - name: Run `packer validate`
        id: validate_packer
        run: "packer validate ./rl9.pkr.hcl"

      - name: Build Image
        id: build_image
        run: packer build ./rl9.pkr.hcl

      - name: Create Resource group
        id: create_resource_group
        run: |
          az group create -n pg-packer-vm -l northeurope

      - name: Create VM
        id: create_vm
        run: az vm create --resource-group pg-packer-vm --location northeurope --name packer-rl9 --image /subscriptions/c6a76d9c-0f67-4a42-b2a1-3defb05f2aae/resourceGroups/rg-packer/providers/Microsoft.Compute/images/rl9 --plan-name rockylinux-x86_64-9 --plan-product rockylinux-x86_64 --plan-publisher resf --admin-username azureuser --generate-ssh-keys

      - name: Open VM port
        id: open_vm_port
        run: |
          az vm open-port \
          --resource-group pg-packer-vm \
          --name packer-rl9 \
          --port 22

#     - name: Run tests
#       run: ssh -i /home/azureuser/.ssh/id_rsa azureuser@myVM 'bash -s' < test-script.sh

#     - name: Shutdown and dismantle VM
#       run: |
#         az vm deallocate --resource-group myResourceGroup --name myVM
#         az vm delete --resource-group myResourceGroup --name myVM --yes