name: Build and Deploy VM

on:
  push:
    branches:
      - main

env:
  PRODUCT_VERSION: "2.0.1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup `packer`
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: ${{ env.PRODUCT_VERSION }}

    - name: Run `packer init`
      id: init_packer
      run: "packer init ./image.pkr.hcl"

    - name: Run `packer validate`
      id: validate_packer
      run: "packer validate ./image.pkr.hcl"

    - name: Build image
      run: packer build rhel.json

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create VM
      run: |
        az group create -n myResourceGroup -l eastus
        az vm create \
        --resource-group myResourceGroup \
        --location eastus \
        --vnet-name myVnet \
        --subnet mySubnet \
        --size Standard_DS1_v2 \
        --name myVM \
        --image myPackerImage \
        --admin-username azureuser \
        --os-disk-name \
        --generate-ssh-keys \

    - name: Run tests
      run: ssh -i /home/azureuser/.ssh/id_rsa azureuser@myVM 'bash -s' < test-script.sh

    - name: Shutdown and dismantle VM
      run: |
        az vm deallocate --resource-group myResourceGroup --name myVM
        az vm delete --resource-group myResourceGroup --name myVM --yes
