# name: Run Tests on Image

# on:
#   workflow_run:
#     workflows: ["Build Image and Run Tests"]
#     types:
#       - completed

# env:
#   VM_USER_NAME: ${{ vars.VM_USER_NAME }}
#   QEMU_IMAGE_OUTPUT_DIR: ${{ vars.QEMU_IMAGE_OUTPUT_DIR }}
#   QCOW2_IMAGE_NAME: ${{ vars.QCOW2_IMAGE_NAME }}

# jobs:
#   run_tests:
#     runs-on: ubuntu-20.04

#     steps:
#       - name: Download image artifact
#         uses: actions/download-artifact@v2
#         with:
#           name: rocky_image
#           path: ${{ QEMU_IMAGE_OUTPUT_DIR }}

#       - name: Run Qemu VM
#         id: run_vm
#         run: |
#           set +x
#           echo "${{ secrets.SSH_PRIVATE_KEY }}" > rocky_rsa
#           set +x
#           chmod 600 rocky_rsa
#           chmod +x scripts/run-vm.sh
#           touch output.json
#           bash scripts/run-vm.sh \
#             -k rocky_rsa \
#             -s scripts/cis-script.sh \
#             -o output.json \
#             -i ${{ QEMU_IMAGE_OUTPUT_DIR }}/${{ QCOW2_IMAGE_NAME }} \
#             -u ${{ VM_USER_NAME}}

#       - name: Upload output as artifact
#         id: cis_test_output
#         uses: actions/upload-artifact@v4
#         with:
#           name: test-output
#           path: output.json

#       - name: Stop and Shutdown a VM
#         id: stop_shutdown_vm
#         run: |
#           chmod +x scripts/shutdown_vm.sh
#           bash scripts/shutdown_vm.sh