name: Run Tests on Image

on:
  workflow_run:
    workflows: ["Build Rl9 Packer Image"]
    types:
      - completed
  push:
    branches:
      - main
      - feature/live_image

env:
  VM_USER_NAME: ${{ vars.VM_USER_NAME }}
  QEMU_IMAGE_OUTPUT_DIR: ${{ vars.QEMU_IMAGE_OUTPUT_DIR }}
  QCOW2_IMAGE_NAME: ${{ vars.QCOW2_IMAGE_NAME }}

jobs:
  run_tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v4

      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: rocky_image
          path: ${{ vars.QEMU_IMAGE_OUTPUT_DIR }}

      - name: Run Qemu VM
        id: run_vm
        run: |
          set +x
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > rocky_rsa
          set -x
          chmod 600 rocky_rsa
          chmod +x scripts/run_vm.sh
          touch output.json
          bash scripts/run_vm.sh -k rocky_rsa -s scripts/cis_script.sh -o output.json -i ${{ vars.QEMU_IMAGE_OUTPUT_DIR }}/${{ vars.QCOW2_IMAGE_NAME }} -u ${{ VM_USER_NAME}}

      - name: Upload test output as artifact
        id: upload_test_output
        uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: output.json

      - name: Shutdown a VM
        id: shutdown_vm
        run: |
          chmod +x scripts/shutdown_vm.sh
          bash scripts/shutdown_vm.sh